### ISSUE TITLE
Invalid command

### ISSUE THREAD

**Issue by ghost** [0301yasiru/YKEY_keylogger#1]
![Screenshot_2020-04-14-01-08-07-819_com termux](https://user-images.githubusercontent.com/43683192/79154069-909a3300-7dec-11ea-871c-974d224958ef.jpg)

**Comment by ghost** [comment]
Oops

**Comment by 0301yasiru** [comment]
Mr Ronalchayengia,
Set is not a individual command but your syntax is invalid. Please help to get help. you have to install the program and configured sql success fully. please follow these guide.

**Comment by 0301yasiru** [comment]
/home/yasiru/Pictures/1.png
/home/yasiru/Pictures/2.png
/home/yasiru/Pictures/3.png

**Comment by 0301yasiru** [comment]
![1](https://user-images.githubusercontent.com/49299881/79205409-87947a80-7e5b-11ea-80e2-13a3bcaa3edc.png)
![2](https://user-images.githubusercontent.com/49299881/79205436-8ebb8880-7e5b-11ea-9876-43166b7dc6e7.png)
![3](https://user-images.githubusercontent.com/49299881/79205447-911de280-7e5b-11ea-89b0-4904f72931db.png)

**Comment by 0301yasiru** [comment]
> Oops

Mr Ronalchayengia,
Set is not a individual command but your syntax is invalid. Please help to get help. you have to install the program and configured sql success fully. please follow these guide.
